lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
# coveralls-ignore-start
  pipeline :api do
    plug :accepts, ["json"]
  end
# coveralls-ignore-stop
  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/posts", PostController, :index
    get "/posts/:id", PostController, :show
    get "/posts/new", PostController, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  # coveralls-ignore-start
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
    end
  # coveralls-ignore-stop
  end
end

lib/blog/application.ex
defmodule Blog.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Blog.Repo,
      # Start the Telemetry supervisor
      BlogWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Blog.PubSub},
      # Start the Endpoint (http/https)
      BlogWeb.Endpoint
      # Start a worker by calling: Blog.Worker.start_link(arg)
      # {Blog.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Blog.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    BlogWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/blog/posts/posts.ex
defmodule Blog.Posts.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
      field :title, :string
      field :description, :string

      timestamps()
    end

    def changeset(post, attrs \\ %{}) do
      post
      |> cast(attrs, [:title, :description])
      |> validate_required([:title, :description], message: "campo obrigatorio")
    end



end

lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo,
    otp_app: :blog,
    adapter: Ecto.Adapters.Postgres
end

lib/blog_web/controllers/page_controller.ex
defmodule BlogWeb.PageController do
  use BlogWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/blog_web/controllers/post_controller.ex
defmodule BlogWeb.PostController do
  use BlogWeb, :controller
  alias Blog.Posts.Post


  def index(conn, _params) do
   posts = Blog.Repo.all(Post)
    render(conn, "post.html",posts: posts)
  end
  def show(conn, %{"id" => id }) do
    post = Blog.Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end
  def new(conn, %{"id" => id }) do
    post = Blog.Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end
end

lib/blog_web/views/error_view.ex
defmodule BlogWeb.ErrorView do
  use BlogWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view
end

lib/blog_web/views/page_view.ex
defmodule BlogWeb.PageView do
  use BlogWeb, :view
end

lib/blog_web/views/post_view.ex
defmodule BlogWeb.PostView do
  use BlogWeb, :view
end

lib/blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Blog · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Blog</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Bem Vindo ALUNO</a></li>
        <li><a href="badges.html">Postar</a></li>
        <li><a href="/posts">Posts</a></li>
      </ul>
    </div>
  </nav>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/blog_web/templates/post/post.html.eex
 <ul class="collection with-header">
        <li class="collection-header"><h4>Posts</h4></li>
        <%= for post <- @posts do %>
        <li class="collection-item">
            <div><%= post.title%>
                <a href="#!" class="secondary-content"><i class="material-icons red-text">delete</i>
                <a href="#!" class="secondary-content"><i class="material-icons green-text">edit</i>
                    <%= link to: Routes.post_path(@conn, :show, post), class: "secondary-content" do %>
                <i class="material-icons blue-text">send</i>
                    <% end %>
                </a>
            </div>
        </li>
        <% end %>
</ul>

  <div class="fixed-action-btn">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">add</i>
  </a>

</div>

lib/blog_web/templates/post/show.html.eex
<div class="col s12 m7">
    <h2 class="header">Horizontal Card</h2>
    <div class="card horizontal">
      <div class="card-image">
        <img src="https://lorempixel.com/100/190/nature/6">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p><%= @post.description %></p>
        </div>
        <div class="card-action">
        <%= link to: Routes.page_path(@conn, :index), class: "btn floating left waves-effect" do %>
            <i class="material-icons">chevron_left</i>
        <% end %>
          <a href="#"><%= @post.title %></a>
          <a href="#"><%= @post.updated_at %></a>
        </div>
      </div>
    </div>
  </div>